export const SECTION_LABELS = {
  contact:    'CONTACT',
  summary:    'PROFESSIONAL SUMMARY',
  experience: 'WORK EXPERIENCE',
  education:  'EDUCATION',
  skills:     'SKILLS',
  languages:  'LANGUAGES',
  projects:   'PROJECTS',
  awards:     'AWARDS',
  certifications: 'CERTIFICATIONS',
  interests:  'INTERESTS',
  publications: 'PUBLICATIONS',
  references: 'REFERENCES',
  volunteer:  'VOLUNTEER',
} as const
